baseURL = "https://rhunter.org"
title = "Rob Hunter"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = "© 2012–2020 Rob Hunter"

theme = "minimo"

logo = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"
titleCaseStyle = "Chicago"

[params.info]
description = ""
title404 = "There's nothing here."

# [params.assets]
# favicon = "favicon.ico"
# customCSS = ["css/custom.css"]
# customJS = ["js/custom.js"]
# gopher = "" # used in 404 template ( Generator: https://gopherize.me )

# [params.copyright]
# prefix = ""
# holder = "Rob Hunter"
# startYear = "2012"
# suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "January 2, 2006"
listDateFormat = "Jan 2, 2006"
archiveDateFormat = "Jan 2"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = false
showLastmod = false
disableToc = false
taxonomyCloudShuffle = false
accentColor = "#800080"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
# header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","sidebar_menu"]
footer = ["social_menu"]


[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "jrh@rhunter.org"
github = "jrhunter"
twitter = "selfactingmule"

[params.comments]
enable = false

# [taxonomies]
# author = "authors"
# category = "categories"
# series = "series"
# tag = "tags"

[permalinks]
page = "/:slug/"

# [[menu.main]]
# name = "Writing"
# weight = -10
# identifier = "writing"
# url = "/writing"
#
# [[menu.main]]
# name = "About"
# weight = -15
# identifier = "about"
# url = "/about"

# [[menu.main]]
# name = "RSS"
# weight = -15
# identifier = "rss"
# url = "/index.xml"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
