baseURL = "http://rhunter.org/"
languageCode = "en-us"
title = "Rob Hunter"
theme = "hugo-notepadium"
description = "Rob Hunter's website"
copyright = "© 2020 Rob Hunter. [Some rights reserved](https://www.gnu.org/licenses/gpl-3.0.en.html)."

buildDrafts = false

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "dark"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = ""
license = ""  # CC License

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.nav]
showCategories = false       # /categories/
showTags = false             # /tags/

# custom navigation items

[[params.nav.custom]]
title = "Writing"
url = "/writing"

[[params.nav.custom]]
title = "About"
url = "/about"
